export const HOSPITALREPORTNUMEDITFORM = 'HOSPITALREPORTNUMEDITFORM'; // 医疗机构报量详情上方表单
export const HOSPITALREPORTNUMEDITTABLE = 'HOSPITALREPORTNUMEDITTABLE';  // 医疗机构报量详情下方表格
export const HOSPITALREPORTNUMCREATEFORM = 'HOSPITALREPORTNUMCREATEFORM'; // 医疗机构报量新增上方表单
export const HOSPITALREPORTNUMCREATETABLE = 'HOSPITALREPORTNUMCREATETABLE';  // 医疗机构报量新增下方表格
